#!/usr/bin/env python3
"""
Test GCodeZAA processing with and without slicer headers
Simulates what happens after ArcWelder strips comments
"""

import sys
sys.path.insert(0, 'GCodeZAA')
from gcodezaa.process import process_gcode

print("=" * 60)
print("GCodeZAA Processing Test - Slicer Detection Fix")
print("=" * 60)

# Test 1: G-code WITH OrcaSlicer header (normal case)
print("\nTest 1: G-code WITH OrcaSlicer header")
print("-" * 60)
gcode_with_header = [
    "; Generated by BambuStudio\n",
    "; Sliced by OrcaSlicer\n",
    "G28\n",
    "G92 X0 Y0 Z0 E0\n",
    "; EXECUTABLE_BLOCK_START\n",
    "G1 X10 Y0 Z0.2 F3000\n",
    "G1 X20 Y0 Z0.2 F3000\n",
    "; EXECUTABLE_BLOCK_END\n",
]

try:
    result1 = process_gcode(gcode_with_header, ".")
    print("✓ Processing succeeded WITH header")
    print(f"  Input lines: {len(gcode_with_header)}")
    print(f"  Output lines: {len(result1)}")
except Exception as e:
    print(f"✗ Processing failed WITH header: {e}")
    sys.exit(1)

# Test 2: G-code WITHOUT slicer header (ArcWelder stripped it)
print("\nTest 2: G-code WITHOUT slicer header (ArcWelder scenario)")
print("-" * 60)
gcode_without_header = [
    "G28\n",
    "G92 X0 Y0 Z0 E0\n",
    "; EXECUTABLE_BLOCK_START\n",
    "G1 X10 Y0 Z0.2 F3000\n",
    "G1 X20 Y0 Z0.2 F3000\n",
    "; EXECUTABLE_BLOCK_END\n",
]

try:
    result2 = process_gcode(gcode_without_header, ".")
    print("✓ Processing succeeded WITHOUT header (FALLBACK WORKS)")
    print(f"  Input lines: {len(gcode_without_header)}")
    print(f"  Output lines: {len(result2)}")
except Exception as e:
    print(f"✗ Processing failed WITHOUT header: {e}")
    sys.exit(1)

# Test 3: G-code with G2/G3 arcs and no header (most realistic scenario)
print("\nTest 3: G-code with G2/G3 arcs, NO header (realistic pipeline)")
print("-" * 60)
gcode_with_arcs = [
    "G28\n",
    "G92 X0 Y0 Z0 E0\n",
    "; EXECUTABLE_BLOCK_START\n",
    "G1 X10 Y0 Z0.2 F3000\n",
    "G2 X20 Y10 I5 J0 E5 F1200\n",
    "G3 X30 Y10 I5 J0 E5 F1200\n",
    "; EXECUTABLE_BLOCK_END\n",
]

try:
    result3 = process_gcode(gcode_with_arcs, ".")
    print("✓ Processing succeeded with arcs and NO header")
    print(f"  Input lines: {len(gcode_with_arcs)}")
    print(f"  Output lines: {len(result3)}")
    arc_count = sum(1 for line in result3 if 'G2 ' in line or 'G3 ' in line)
    print(f"  Arc commands preserved: {arc_count}")
except Exception as e:
    print(f"✗ Processing failed with arcs and NO header: {e}")
    sys.exit(1)

print("\n" + "=" * 60)
print("✓ All GCodeZAA processing tests PASSED")
print("=" * 60)
print("\nConclusion:")
print("- Slicer detection works WITH headers")
print("- Fallback to OrcaSlicer works WITHOUT headers (ArcWelder scenario)")
print("- Arc processing works in both cases")
print("- Pipeline is robust for production use")
