#!/usr/bin/env python3
"""Tests for slicer auto-detection and fallback behavior."""

import sys

sys.path.insert(0, "GCodeZAA")

from gcodezaa.slicer_syntax import Slicer


def test_detect_orcaslicer_header():
    gcode = ["; Generated by OrcaSlicer", "G1 X10 Y10"]
    assert Slicer.detect(gcode) == Slicer.ORCA


def test_detect_no_header_falls_back_to_orca():
    gcode = ["G1 X10 Y10", "G2 X20 Y20 I5 J5"]
    assert Slicer.detect(gcode) == Slicer.ORCA


def test_detect_prusaslicer_header():
    gcode = ["; Generated by PrusaSlicer", "G1 X10 Y10"]
    assert Slicer.detect(gcode) == Slicer.PRUSA


def test_detect_bambustudio_header():
    gcode = ["; Generated by BambuStudio", "G1 X10 Y10"]
    assert Slicer.detect(gcode) == Slicer.BAMBU
