#!/usr/bin/env python3
"""
Integration test for G2/G3 arc support in GCodeZAA
Tests that arcs are properly processed through the full pipeline
"""

import sys
import os

sys.path.insert(0, 'GCodeZAA')

from gcodezaa.process import process_gcode

def test_g_code_with_arcs():
    """Test G-code processing that includes arc commands"""
    print("Test: GCodeZAA full pipeline with G2/G3 arcs")
    print("-" * 60)
    
    # Sample G-code with arcs (Bambulab format with proper header)
    gcode = [
        "; Generated by BambuStudio\n",
        "; Printer_type: X1C\n",
        "M109 S0 ; Set nozzle temp\n",
        "G28\n",
        "G92 X0 Y0 Z0 E0\n",
        "; EXECUTABLE_BLOCK_START\n",
        "G1 X10 Y0 Z0.2 F3000 ; Move to start\n",
        "G2 X20 Y10 I10 J0 E5 F1200 ; Clockwise arc (quarter circle)\n",
        "G3 X30 Y10 I5 J0 E5 F1200 ; Counter-clockwise arc\n",
        "G1 Z0.4 F1200 ; Change Z\n",
        "G0 X0 Y0 ; Return to origin\n",
        "; EXECUTABLE_BLOCK_END\n",
    ]
    
    # Process without model (no ZAA analysis)
    try:
        result = process_gcode(gcode, ".")
        
        print("✓ G-code processed successfully")
        print(f"✓ Input lines: {len(gcode)}")
        print(f"✓ Output lines: {len(result)}")
        
        # Verify arc commands are preserved in output
        arc_commands = [line for line in result if 'G2 ' in line or 'G3 ' in line]
        print(f"✓ Arc commands in output: {len(arc_commands)}")
        
        for i, line in enumerate(result):
            if 'G2 ' in line or 'G3 ' in line:
                print(f"  Line {i}: {line.strip()}")
        
        print()
        print("✓ Full pipeline integration test PASSED")
        return True
        
    except Exception as e:
        print(f"✗ Test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

def test_arc_parameter_parsing():
    """Test that arc parameters are correctly parsed"""
    print("Test: Arc parameter parsing")
    print("-" * 60)
    
    from gcodezaa.process import parse_simple_args
    
    test_cases = [
        ("G2 X10 Y20 I5 J5 F1200", {"X": "10", "Y": "20", "I": "5", "J": "5", "F": "1200"}),
        ("G3 X30 Y40 R10 E2.5", {"X": "30", "Y": "40", "R": "10", "E": "2.5"}),
        ("G2 X5 Y5 Z0.2 I2.5 J2.5 E1 F2000", {"X": "5", "Y": "5", "Z": "0.2", "I": "2.5", "J": "2.5", "E": "1", "F": "2000"}),
    ]
    
    for gcode_line, expected in test_cases:
        args = parse_simple_args(gcode_line)
        
        # Remove G2/G3 from args (it's always there)
        if "G2" in args:
            del args["G2"]
        if "G3" in args:
            del args["G3"]
        
        matching = all(args.get(k) == v for k, v in expected.items())
        
        if matching:
            print(f"  ✓ {gcode_line[:40]}")
        else:
            print(f"  ✗ {gcode_line[:40]}")
            print(f"    Expected: {expected}")
            print(f"    Got: {args}")
            return False
    
    print("✓ Parameter parsing test PASSED")
    print()
    return True

def test_arc_safety_validation():
    """Test safety checks for arc parameters"""
    print("Test: Arc safety validation")
    print("-" * 60)
    
    from gcodezaa.extrusion import decompose_arc
    import math
    
    # Test 1: Reasonable arc radius
    start = (0.0, 0.0, 0.0)
    waypoints = decompose_arc(
        start_pos=start,
        end_x=10.0,
        end_y=10.0,
        end_z=0.0,
        radius=10.0,
        segment_length=0.5  # More segments for safety
    )
    
    # Verify waypoints stay within reasonable bounds
    for wp in waypoints:
        assert not math.isnan(wp[0]) and not math.isnan(wp[1]), "Invalid waypoint detected"
    
    print("  ✓ Arc validity check passed")
    
    # Test 2: Extreme radius (should still work)
    waypoints = decompose_arc(
        start_pos=start,
        end_x=0.1,  # Very short arc
        end_y=0.1,
        end_z=0.0,
        radius=100.0,  # Large radius
        segment_length=0.5
    )
    
    assert len(waypoints) > 0, "Extreme radius arc decomposition failed"
    print("  ✓ Extreme arc parameters handled safely")
    
    print("✓ Safety validation test PASSED")
    print()
    return True

if __name__ == "__main__":
    print()
    print("=" * 60)
    print("G2/G3 Integration Tests for GCodeZAA")
    print("=" * 60)
    print()
    
    all_passed = True
    
    all_passed &= test_arc_parameter_parsing()
    all_passed &= test_arc_safety_validation()
    all_passed &= test_g_code_with_arcs()
    
    print("=" * 60)
    if all_passed:
        print("✓ All integration tests PASSED")
    else:
        print("✗ Some tests FAILED")
    print("=" * 60)
    print()
    
    sys.exit(0 if all_passed else 1)
