#!/usr/bin/env python3
"""Tests for GCodeZAA processing with and without slicer headers."""

import sys

sys.path.insert(0, "GCodeZAA")

from gcodezaa.process import process_gcode


def test_process_gcode_with_header_succeeds():
    gcode_with_header = [
        "; Generated by BambuStudio\n",
        "; Sliced by OrcaSlicer\n",
        "G28\n",
        "G92 X0 Y0 Z0 E0\n",
        "; EXECUTABLE_BLOCK_START\n",
        "G1 X10 Y0 Z0.2 F3000\n",
        "G1 X20 Y0 Z0.2 F3000\n",
        "; EXECUTABLE_BLOCK_END\n",
    ]

    result = process_gcode(gcode_with_header, ".")
    assert len(result) == len(gcode_with_header)


def test_process_gcode_without_header_succeeds():
    gcode_without_header = [
        "G28\n",
        "G92 X0 Y0 Z0 E0\n",
        "; EXECUTABLE_BLOCK_START\n",
        "G1 X10 Y0 Z0.2 F3000\n",
        "G1 X20 Y0 Z0.2 F3000\n",
        "; EXECUTABLE_BLOCK_END\n",
    ]

    result = process_gcode(gcode_without_header, ".")
    assert len(result) == len(gcode_without_header)


def test_process_gcode_with_arcs_and_no_header_preserves_arcs():
    gcode_with_arcs = [
        "G28\n",
        "G92 X0 Y0 Z0 E0\n",
        "; EXECUTABLE_BLOCK_START\n",
        "G1 X10 Y0 Z0.2 F3000\n",
        "G2 X20 Y10 I5 J0 E5 F1200\n",
        "G3 X30 Y10 I5 J0 E5 F1200\n",
        "; EXECUTABLE_BLOCK_END\n",
    ]

    result = process_gcode(gcode_with_arcs, ".")
    arc_count = sum(1 for line in result if "G2 " in line or "G3 " in line)
    assert arc_count >= 2


def test_process_gcode_without_executable_markers_succeeds():
    gcode_without_markers = [
        "; Generated by OrcaSlicer\n",
        "G28\n",
        "G92 X0 Y0 Z0 E0\n",
        "G1 X10 Y0 Z0.2 F3000\n",
        "G1 X20 Y0 Z0.2 F3000\n",
    ]

    result = process_gcode(gcode_without_markers, ".")

    assert len(result) == len(gcode_without_markers)
    assert result[0] == gcode_without_markers[0]
