#!/usr/bin/env python3
"""
Test slicer detection with and without headers
Verifies the fallback to OrcaSlicer works correctly
"""

import sys
sys.path.insert(0, 'GCodeZAA')
from gcodezaa.slicer_syntax import Slicer

# Test 1: Direct slicer detection with OrcaSlicer header
test1 = ['; Generated by OrcaSlicer', 'G1 X10 Y10']
result1 = Slicer.detect(test1)
status1 = "PASS" if result1 == Slicer.ORCA else "FAIL"
print(f'Test 1 (OrcaSlicer header): {result1} - {status1}')

# Test 2: No slicer header (ArcWelder stripped it) - FALLBACK TEST
test2 = ['G1 X10 Y10', 'G2 X20 Y20 I5 J5']
result2 = Slicer.detect(test2)
status2 = "PASS" if result2 == Slicer.ORCA else "FAIL"
print(f'Test 2 (No header - fallback): {result2} - {status2}')

# Test 3: PrusaSlicer header
test3 = ['; Generated by PrusaSlicer', 'G1 X10 Y10']
result3 = Slicer.detect(test3)
status3 = "PASS" if result3 == Slicer.PRUSA else "FAIL"
print(f'Test 3 (PrusaSlicer header): {result3} - {status3}')

# Test 4: BambuStudio header
test4 = ['; Generated by BambuStudio', 'G1 X10 Y10']
result4 = Slicer.detect(test4)
status4 = "PASS" if result4 == Slicer.BAMBU else "FAIL"
print(f'Test 4 (BambuStudio header): {result4} - {status4}')

all_passed = all([status1 == "PASS", status2 == "PASS", status3 == "PASS", status4 == "PASS"])
print(f'\nAll slicer detection tests: {"PASSED" if all_passed else "FAILED"}')
sys.exit(0 if all_passed else 1)
